orbs:
  win: circleci/windows@2.4.0

executors:
  linux:
    docker:
      - image: circleci/node:12-browsers
  mac:
    macos:
      xcode: "11.3.1"

version: 2.1

jobs:
  package:
    parameters:
      platform:
        type: string
    executor: << parameters.platform >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ arch }}
      - run:
          name: 依存関係のインストール
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - when:
          condition:
            not:
              equal: [ << parameters.platform >>, win/default ]
          steps:
            - run:
                name: << parameters.platform >>向けパッケージを作成
                command: npx electron-builder --<< parameters.platform >> --publish never
      - when:
          condition:
            equal: [ << parameters.platform >>, win/default ]
          steps:
            - run:
                name: Windows向けパッケージの作成
                command: npx electron-builder --win --publish never
      - persist_to_workspace:
          root: ./
          paths:
            - dist

  release:
    executor: linux
    steps:
      - attach_workspace:
          at: ./
      - store_artifacts:
          path: dist

workflows:
  version: 2
  package-and-release:
    jobs:
      - package:
          matrix:
            parameters:
              platform: [linux, win/default]
              # platform: [linux, win/default, mac]
              # mac Executorは有償プランのみ使用できます
      - release:
          requires: [package]
